sudo: required
dist: xenial

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  


services:
  - xvfb

install:
  - pip install pytest>=3.6 pycodestyle python-coveralls pytest_cov==2.5


script: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then make coveralls;
	else make test;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then coveralls;
    fi

notifications:
  email: false
